---
- name: Display _qemu_img
  ansible.builtin.debug:
    msg: "_qemu_img = {{ _qemu_img }}"
  tags:
    - never
    - debug

- name: Display the disk
  ansible.builtin.debug:
    msg: "disk = {{ _disk }}"
  tags:
    - never
    - debug

- name: Create _qemu_img_disk
  ansible.builtin.set_fact:
    _qemu_img_disk:
      dest:
        "{{ _vm.path }}/{{ _disk.name }}"
      owner: "{{ _security.file.owner }}"
      group: "{{ _security.file.group }}"
      mode: "{{ _security.file.mode }}"

- name: Combine
  ansible.builtin.set_fact:
    _qemu_img_disk:
      "{{ _qemu_img_disk | combine(_disk) }}"

- name: Display the _qemu_img_disk
  ansible.builtin.debug:
    msg: "_qemu_img_disk = {{ _qemu_img_disk }}"
  tags:
    - never
    - debug

- name: Add the disk to the qemu_img array
  ansible.builtin.set_fact:
    _qemu_img:
      "{{ _qemu_img + [_qemu_img_disk] }}"
