---
#
# Create the vm destination directory if not exists
#
- name: "Verify if  vm.path exists {{ vm.path }}"
  ansible.builtin.stat:
    path:
      "{{ vm.path }}"
  register:
    stat_vm_path

- name: "Create {{ vm.path }}"
  ansible.builtin.file:
    path:
      "{{ vm.path }}"
    owner:
      "{{ _security.dir.owner }}"
    group:
      "{{ _security.dir.group }}"
    mode:
      "{{ _security.dir.mode }}"
    recurse: true
  when:
    - not stat_vm_path.stat.exists
