---
- name: Display the hostname
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }}"
  tags:
    - debug
    - never

- name: Set the hostname
  ansible.builtin.hostname:
    name:
      "{{ inventory_hostname }}"

- name: Setup the etc_hosts var
  ansible.builtin.set_fact:
    etc_hosts:
      hosts:
        - { name: "debian.*", ip: "127.0.1.1", state: "absent" }
        - { name: "{{ inventory_hostname }}", ip: "{{ ansible_default_ipv4.address }}", state: "present" }

- name: Include etc_hosts role
  ansible.builtin.include_role:
    name:
      stafwag.etc_hosts
