---
- name: Verify if vm_kvm_host is defined
  ansible.builtin.fail:
    msg:
      - "Sorry, I need the vm_kvm_host variable to continue"
  when:
    - vm_kvm_host is not defined

#
# It's required to have the facts for the vm_kvm_hosts
# to able to install the necessary packages with the roles
# that are called from this role.
#
# run_once is setup only to get the facts once when the role
# is executed multiple times. e.g. During a delegated_to execution.
#
- name: Gather facts on {{ vm_kvm_host }}
  ansible.builtin.setup:
  delegate_to: "{{ vm_kvm_host }}"
  run_once: true
  tags:
    - install

- name: Install the virtual machines
  ansible.builtin.import_tasks: delegate_vms.yml
  delegate_to: "{{ vm_kvm_host }}"

- name: Wait for the nodes to come online
  ansible.builtin.include_tasks: wait.yml
  when:
    - virt_install_vm_installed

- name: Post actions
  ansible.builtin.include_tasks: post.yml
  when:
    - virt_install_vm_installed or
      _post.always

- name: Wait for the nodes to come online
  ansible.builtin.include_tasks: wait.yml
