---
- name: Verify if vm_kvm_host is defined
  fail:
    msg:
      - "Sorry, I need the vm_kvm_host variable to continue"
  when:
    - vm_kvm_host is not defined

#
# It's required to have the facts for the vm_kvm_hosts
# to able to install the required packages with the roles
# that are called from this role.
#
- name: Gather facts on {{ vm_kvm_host }}
  setup:
  delegate_to: "{{ vm_kvm_host }}"
  tags:
    - install

- name: Install the virtual machines
  import_tasks: delegate_vms.yml
  delegate_to: "{{ vm_kvm_host }}"

- name: Wait for the nodes to come online
  include_tasks: wait.yml
  when:
    - virt_install_vm_installed

- name: Post actions 
  include_tasks: post.yml
  when:
    - virt_install_vm_installed or
      _post.always

- name: Wait for the nodes to come online
  include_tasks: wait.yml
