---
- name: Post configuration started
  ansible.builtin.debug:
    msg:
      - "Post configuration started"
  tags:
    - never
    - debug

- name: Display _post
  ansible.builtin.debug:
    msg:
      - "_post: {{ _post }}"
  tags:
    - never
    - debug

- name: Display virt_install_vm_installed
  ansible.builtin.debug:
    msg:
      - "virt_install_vm_installed: {{ virt_install_vm_installed }}"
  tags:
    - never
    - debug

- name: Update etc_hosts
  when:
    - _post.update_etc_hosts
  block:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Setup etc hosts
      ansible.builtin.include_tasks: etc_hosts.yml

- name: Update ssh known_hosts
  ansible.builtin.include_tasks: update_ssh_known_hosts.yml
  when:
    - _post.update_ssh_known_hosts
    - virt_install_vm_installed

- name: Update the all packages
  ansible.builtin.import_role:
    name:
      stafwag.package_update
  notify:
    Reboot_after_update
  when:
    - _post.package_update

- name: Flush handlers to force the reboot handler
  ansible.builtin.meta:
    flush_handlers
