---
- name: Post configuration started
  debug:
    msg:
      - " ost configuration started"
  tags:
    - never
    - debug

- name: Display _post
  debug:
    msg:
      - "_post: {{ _post }}"
  tags:
    - never
    - debug

- name: Display virt_install_vm_installed
  debug:
    msg:
      - "virt_install_vm_installed: {{ virt_install_vm_installed }}"
  tags:
    - never
    - debug

- name: Update etc_hosts
  block:
    - name: Gather facts
      setup:

    - name: Setup etc hosts
      include_tasks: etc_hosts.yml
  when:
    - _post.update_etc_hosts

- name: Update ssh known_hosts
  include_tasks: update_ssh_known_hosts.yml
  when:
    - _post.update_ssh_known_hosts
    - virt_install_vm_installed

- name: Update the all packages
  import_role:
    name:
      stafwag.package_update
  notify:
      reboot_after_update
  when:
    - _post.package_update

- name: Flush handlers to force the reboot handler
  meta:
    flush_handlers
