---
- name: Debug display ansible host
  ansible.builtin.debug:
    msg:
      - "ansible_host: {{ ansible_host }}"
  tags:
    - never
    - debug

# Update ssh host key in known_hosts
#
# Set become to false
# ssh connection will be established as the "normal" ansible
# user normally
#
# throttle to 1, to avoid that the ssh host key remove fails because the
# known_hosts.old already exsists
- name: Remove ssh host key in known_hosts
  delegate_to: localhost
  become: false
  throttle: 1
  ansible.builtin.known_hosts:
    name: "{{ ansible_host }}"
    state: absent

- name: Ping the hosts to update .ssh/known_hosts
  delegate_to: localhost
  become: false
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  ansible.builtin.ping:
